# sites:
#   cnn:
#     base_url: "https://edition.cnn.com"
#     categories:
#       world: "world"
#       business: "business"
#       markets: "markets"
#       health: "health"
#       entertainment: "entertainment"
#       tech: "tech"
#       style: "style"
#       travel: "travel"
#       sports: "sports"
#       science: "science"
#       climate: "climate"
#       weather: "weather"

#   bbc:
#     base_url: "https://www.bbc.com" # BBCCollector의 base_url과 일치
#     categories:
#       news: "news"  
#       sport: "sport" 
#       business: "business"
#       innovation: "innovation"
#       culture: "culture"   
#       arts: "culture/arts"  
#       travel: "travel" 
#       earth: "future-planet"

#   the_guardian:
#     base_url: "https://www.theguardian.com"
#     categories:
#       world: "world"
#       science: "science"
#       lifeandstyle: "uk/lifeandstyle"
#       culture: "uk/culture"
#       sport: "uk/sport"
#       football: "football"
#       technology: "uk/technology"
#       business: "uk/business"

#   # npr:
#   #   base_url: "https://www.npr.org"
#   #   categories:
#   #     world: "sections/world"
#   #     business: "sections/business"
#   #     climate: "sections/climate"
#   #     science: "sections/science"
#   #     health: "sections/health"
#   #     culture: "sections/culture"

#   # NYT도 동적 클래스때문에 크롤링이 쉽지 않음.... 그래서 아마 API 사용해야 할듯 함.
#   # API 이용해서 해보려 했지만, API 이용해서 하려고 해도 구독이 필수적이라 포기함.
#   # nyt:
#   #   # base_url은 collector 내부에 Archive API URL로 설정되어 있으므로 여기선 주석 처리하거나 삭제해도 무방합니다.
#   #   # base_url: "https://api.nytimes.com/svc/archive/v1" 
#   #   categories:
#   #     "NYT World": "world"
#   #     "NYT Business": "business"
#   #     "NYT Arts": "arts"
#   #     "NYT Lifestyle": "t-magazine" # 또는 "style", "fashion", "food" 등 NYT 제공 섹션
#   #     "NYT Politics": "politics"
#   #     "NYT Tech": "technology"
#   #     "NYT Climate": "science"    # 'climate' 섹션 대안
#   #     "NYT Health": "health"
#   #     "NYT Culture": "opinion"    # 'culture' 관련 섹션 대안

#   # ap: # AP News 설정 제거 (현재 진행하지 않음 = 403 forbidden 때문에)
#   #   base_url: "https://apnews.com"
#   #   categories:
#   #     politics: "politics"
#   #     world: "world-news"
#   #     sports: "sports"
#   #     entertainment: "entertainment"
#   #     business: "business"
#   #     science: "science"
#   #     technology: "technology"
#   #     health: "health"
#   #     lifestyle: "lifestyle"

  
#   # reuters:
#   #   base_url: "https://www.reuters.com"
#   #   categories:
#   #     world: "world"
#   #     business: "business"
#   #     markets: "markets"
#   #     technology: "technology"
#   #     sports: "sports" 
#   #     science: "science" 
#   #     lifestyle: "lifestyle"


  