sites:
  cnn:
    base_url: "https://edition.cnn.com"
    categories:
      world: "world"
      business: "business"
      #markets: "markets"
      #health: "health"
      #entertainment: "entertainment"
      technology: ["tech","science"]
      #style: "style"
      #travel: "travel"
      sports: "sports"
      #climate: "climate"
      #weather: "weather"

  # bbc:
  #   base_url: "https://www.bbc.com" # BBCCollector의 base_url과 일치
  #   categories:
  #     world: "news"  
  #     sports: "sport" 
  #     business: "business"
  #     technology: ["innovation/technology","innovation/artificial-intelligence"]
  #     culture: "culture"   
  #     # arts: "culture/arts"  
  #     # travel: "travel" 
  #     #earth: "future-planet"

  # the_guardian:
  #   base_url: "https://www.theguardian.com"
  #   categories:
  #     world: "world"
  #     # lifeandstyle: "uk/lifeandstyle"
  #     culture: "uk/culture"
  #     sports: ["uk/sport","football"]
  #     # football: "football"
  #     technology: ["uk/technology","science"]
  #     business: "uk/business"
  # # Reuter, NPR, NYT는 안돼서 없애놨음
  # the_times:
  #   base_url: "https://www.thetimes.co.uk"
  #   categories:
  #     world: "world"
  #     #life-style: "life-style" 
  #     business: "business-money" 
  #     sports: "sport"
  #     culture: "culture"
  # #완료
  # yonhap:
  #   base_url: "https://www.yna.co.kr"
  #   categories:
  #     politics: "politics/all"
  #     economy: "economy/all" 
  #     national: ["society/all","local/all"]
  #     world: "international/all" 
  #     culture: "culture/all" 
  #     sports: "sports/all" 
  #     technology: "industry/technology-science" 

  # chosun:
  #   base_url: "https://www.chosun.com"
  #   categories:
  #     politics: "politics" 
  #     economy: "economy"
  #     national: "national" 
  #     world: "international" 
  #     culture: "culture-style" 
  #     sports: "sports" 

  # joongang:
  #   base_url: "https://www.joongang.co.kr"
  #   categories:
  #     politics: "politics" 
  #     economy: "money" 
  #     national: "society" 
  #     world: "world" 
  #     culture: "culture" 
  #     sports: "sports" 

  # donga:
  #   base_url: "https://www.donga.com"
  #   categories:
  #     politics: "news/Politics" # 경로 대소문자 수정
  #     economy: "news/Economy" 
  #     national: "news/Society" 
  #     world: "news/Inter" 
  #     culture: "news/Culture" 
  #     sports: "news/Sports" 

  # hankyoreh:
  #   base_url: "https://www.hani.co.kr"
  #   categories:
  #     politics: "arti/politics" 
  #     economy: "arti/economy" 
  #     national: ["arti/society","arti/area"] 
  #     world: "arti/international" 
  #     culture: "arti/culture" 
  #     sports: "arti/sports" 

  # kyunghyang:
  #   base_url: "https://www.khan.co.kr"
  #   categories:
  #     politics: "politics" 
  #     economy: "economy" 
  #     national: "national" 
  #     world: "world" 
  #     culture: "culture" 
  #     sports: "sports" 
  